#! /bin/sh

bspc monitor DP-4 -d 1 2 3 4 5
bspc monitor HDMI-0 -d 6 7 8 9 0
bspc wm -O DP-4 HDMI-0

bspc config border_width 3
bspc config window_gap 10
bspc config split_ratio 0.50

bspc config focused_border_color "#7bc5e4"
bspc config normal_border_color "#32344a"
bspc config active_border_color "#444b6a"

bspc config borderless_monocle true
bspc config gapless_monocle true
# bspc config paddingless_monocle true
bspc config single_monocle false
bspc config focus_follows_pointer true

bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_corner

pgrep -x sxhkd > /dev/null || sxhkd &

xrdb -merge $HOME/.Xresources

~/.fehbg &

bash "$HOME"/.config/polybar/launch.sh &

while pgrep -u $UID -x picom > /dev/null; do sleep 1; done
picom &

lxsession &

pkill -9 -f "dunst"
dunstify -i window_list "Successfully restarted BSPWM"
