#! /bin/sh

setxkbmap -layout de &
sxhkd &
compton --config ~/.config/compton/compton.conf &
feh --bg-scale Pictures/Wallpaper.jpg &
exec ~/.config/polybar/launch.sh &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         5
bspc config window_gap          10

bspc config normal_border_color \#006644
bspc config focused_border_color \#00FFAB
bspc config urgent_border_color \#B58900
bspc config presel_border_color \#14EC97


bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

bspc config top_padding 30
bspc config bottom_padding 0
bspc config left_padding 0
bspc config right_padding 0
bspc config border_radius 40
